version: '3.1'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecret
      POSTGRES_USER: myuser
      POSTGRES_DB: elixir_db
    ports:
      - "5432:5432"
      